export const FLIGHTS_LOAD: string = 'FLIGHTS/LOAD';
export const FLIGHTS_LOAD_SUCCESS: string = 'FLIGHTS/LOAD_SUCCESS';
export const FLIGHTS_SORT: string = 'FLIGHTS/SORT';
export const FLIGHTS_FILTER_NO_TRANSFER: string = 'FLIGHTS/FILTER/NOTRANSFER';
export const FLIGHTS_FILTER_ONE_TRANSFER: string = 'FLIGHTS/FILTER/ONETRANSFER';
export const FLIGHTS_FILTER_PRICE_FROM_TO: string = 'FLIGHTS/FILTER/PRICEFROMTO';
export const FLIGHTS_FILTER_CARRIERS: string = 'FLIGHTS/FILTER/CARRIERS';
export const FLIGHTS_ADD_SHOW_FLIGHTS: string = 'FLIGHTS/ADD_SHOW_FLIGHTS';
